VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "StockStatistics"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public MaxIncrease As Double

Public MaxIncreaseTicker As String

Public MaxDecrease As Double

Public MaxDecreaseTicker As String

Public MaxTotalVolume As Double

Public MaxTotalVolumeTicker As String
